### PR TITLE
Add support for importing this library as an esm module

### PR DESCRIPTION
**Pull request by DevMude**
As a fix for https://github.com/LilyRose2798/trpc-openapi/issues/6

### CODE REVIEW

**Comment by DevMude** [comment]
So this fix is also necessary if you want to use next v14+

The custom rename.js script is a bit hacky. I'm sure you could use a proper build tool to solve the issue, but I didn't want to mess with the build process too much, so this works for now.

**Comment by DevMude** [comment]
@LilyRose2798 any chance you could take a look at this?

**Comment by LilyRose2798** [comment]
Looks good. Will merge it now.

**Comment by LilyRose2798** [comment]
Published on npm as v1.4.0

**Pull request merged**
